/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as hybridRouteRouteImport } from './routes/(hybrid)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as hybridUnauthorizedRouteImport } from './routes/(hybrid)/unauthorized'
import { Route as privatedashboardRouteRouteImport } from './routes/(private)/(dashboard)/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as privatedashboardQaIndexRouteImport } from './routes/(private)/(dashboard)/qa/index'
import { Route as privatedashboardDashboardIndexRouteImport } from './routes/(private)/(dashboard)/dashboard/index'
import { Route as privatedashboardQaTestsIndexRouteImport } from './routes/(private)/(dashboard)/qa/tests/index'
import { Route as privatedashboardQaEnvironmentIndexRouteImport } from './routes/(private)/(dashboard)/qa/environment/index'
import { Route as privatedashboardQaDefectsIndexRouteImport } from './routes/(private)/(dashboard)/qa/defects/index'
import { Route as privatedashboardQaTestsTestIdIndexRouteImport } from './routes/(private)/(dashboard)/qa/tests/$testId/index'
import { Route as privatedashboardQaDefectsDefectIdIndexRouteImport } from './routes/(private)/(dashboard)/qa/defects/$defectId/index'
import { Route as privatedashboardQaCampaignsCampaignIdIndexRouteImport } from './routes/(private)/(dashboard)/qa/campaigns/$campaignId/index'
import { Route as privatedashboardQaTestsTestIdRunRouteImport } from './routes/(private)/(dashboard)/qa/tests/$testId/run'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const hybridRouteRoute = hybridRouteRouteImport.update({
  id: '/(hybrid)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const hybridUnauthorizedRoute = hybridUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => hybridRouteRoute,
} as any)
const privatedashboardRouteRoute = privatedashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privatedashboardQaIndexRoute = privatedashboardQaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => privatedashboardRouteRoute,
} as any)
const privatedashboardDashboardIndexRoute =
  privatedashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaTestsIndexRoute =
  privatedashboardQaTestsIndexRouteImport.update({
    id: '/qa/tests/',
    path: '/qa/tests/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaEnvironmentIndexRoute =
  privatedashboardQaEnvironmentIndexRouteImport.update({
    id: '/qa/environment/',
    path: '/qa/environment/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaDefectsIndexRoute =
  privatedashboardQaDefectsIndexRouteImport.update({
    id: '/qa/defects/',
    path: '/qa/defects/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaTestsTestIdIndexRoute =
  privatedashboardQaTestsTestIdIndexRouteImport.update({
    id: '/qa/tests/$testId/',
    path: '/qa/tests/$testId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaDefectsDefectIdIndexRoute =
  privatedashboardQaDefectsDefectIdIndexRouteImport.update({
    id: '/qa/defects/$defectId/',
    path: '/qa/defects/$defectId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaCampaignsCampaignIdIndexRoute =
  privatedashboardQaCampaignsCampaignIdIndexRouteImport.update({
    id: '/qa/campaigns/$campaignId/',
    path: '/qa/campaigns/$campaignId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardQaTestsTestIdRunRoute =
  privatedashboardQaTestsTestIdRunRouteImport.update({
    id: '/qa/tests/$testId/run',
    path: '/qa/tests/$testId/run',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/unauthorized': typeof hybridUnauthorizedRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof privatedashboardDashboardIndexRoute
  '/qa/': typeof privatedashboardQaIndexRoute
  '/qa/defects/': typeof privatedashboardQaDefectsIndexRoute
  '/qa/environment/': typeof privatedashboardQaEnvironmentIndexRoute
  '/qa/tests/': typeof privatedashboardQaTestsIndexRoute
  '/qa/tests/$testId/run': typeof privatedashboardQaTestsTestIdRunRoute
  '/qa/campaigns/$campaignId/': typeof privatedashboardQaCampaignsCampaignIdIndexRoute
  '/qa/defects/$defectId/': typeof privatedashboardQaDefectsDefectIdIndexRoute
  '/qa/tests/$testId/': typeof privatedashboardQaTestsTestIdIndexRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof hybridUnauthorizedRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof privatedashboardDashboardIndexRoute
  '/qa': typeof privatedashboardQaIndexRoute
  '/qa/defects': typeof privatedashboardQaDefectsIndexRoute
  '/qa/environment': typeof privatedashboardQaEnvironmentIndexRoute
  '/qa/tests': typeof privatedashboardQaTestsIndexRoute
  '/qa/tests/$testId/run': typeof privatedashboardQaTestsTestIdRunRoute
  '/qa/campaigns/$campaignId': typeof privatedashboardQaCampaignsCampaignIdIndexRoute
  '/qa/defects/$defectId': typeof privatedashboardQaDefectsDefectIdIndexRoute
  '/qa/tests/$testId': typeof privatedashboardQaTestsTestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(hybrid)': typeof hybridRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/(dashboard)': typeof privatedashboardRouteRouteWithChildren
  '/(hybrid)/unauthorized': typeof hybridUnauthorizedRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(private)/(dashboard)/dashboard/': typeof privatedashboardDashboardIndexRoute
  '/(private)/(dashboard)/qa/': typeof privatedashboardQaIndexRoute
  '/(private)/(dashboard)/qa/defects/': typeof privatedashboardQaDefectsIndexRoute
  '/(private)/(dashboard)/qa/environment/': typeof privatedashboardQaEnvironmentIndexRoute
  '/(private)/(dashboard)/qa/tests/': typeof privatedashboardQaTestsIndexRoute
  '/(private)/(dashboard)/qa/tests/$testId/run': typeof privatedashboardQaTestsTestIdRunRoute
  '/(private)/(dashboard)/qa/campaigns/$campaignId/': typeof privatedashboardQaCampaignsCampaignIdIndexRoute
  '/(private)/(dashboard)/qa/defects/$defectId/': typeof privatedashboardQaDefectsDefectIdIndexRoute
  '/(private)/(dashboard)/qa/tests/$testId/': typeof privatedashboardQaTestsTestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/api/auth/$'
    | '/dashboard/'
    | '/qa/'
    | '/qa/defects/'
    | '/qa/environment/'
    | '/qa/tests/'
    | '/qa/tests/$testId/run'
    | '/qa/campaigns/$campaignId/'
    | '/qa/defects/$defectId/'
    | '/qa/tests/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/api/auth/$'
    | '/dashboard'
    | '/qa'
    | '/qa/defects'
    | '/qa/environment'
    | '/qa/tests'
    | '/qa/tests/$testId/run'
    | '/qa/campaigns/$campaignId'
    | '/qa/defects/$defectId'
    | '/qa/tests/$testId'
  id:
    | '__root__'
    | '/(hybrid)'
    | '/(private)'
    | '/(public)'
    | '/(private)/(dashboard)'
    | '/(hybrid)/unauthorized'
    | '/(public)/forgot-password'
    | '/(public)/login'
    | '/(public)/'
    | '/api/auth/$'
    | '/(private)/(dashboard)/dashboard/'
    | '/(private)/(dashboard)/qa/'
    | '/(private)/(dashboard)/qa/defects/'
    | '/(private)/(dashboard)/qa/environment/'
    | '/(private)/(dashboard)/qa/tests/'
    | '/(private)/(dashboard)/qa/tests/$testId/run'
    | '/(private)/(dashboard)/qa/campaigns/$campaignId/'
    | '/(private)/(dashboard)/qa/defects/$defectId/'
    | '/(private)/(dashboard)/qa/tests/$testId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  hybridRouteRoute: typeof hybridRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hybrid)': {
      id: '/(hybrid)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof hybridRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(hybrid)/unauthorized': {
      id: '/(hybrid)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof hybridUnauthorizedRouteImport
      parentRoute: typeof hybridRouteRoute
    }
    '/(private)/(dashboard)': {
      id: '/(private)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)/qa/': {
      id: '/(private)/(dashboard)/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof privatedashboardQaIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/dashboard/': {
      id: '/(private)/(dashboard)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof privatedashboardDashboardIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/tests/': {
      id: '/(private)/(dashboard)/qa/tests/'
      path: '/qa/tests'
      fullPath: '/qa/tests/'
      preLoaderRoute: typeof privatedashboardQaTestsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/environment/': {
      id: '/(private)/(dashboard)/qa/environment/'
      path: '/qa/environment'
      fullPath: '/qa/environment/'
      preLoaderRoute: typeof privatedashboardQaEnvironmentIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/defects/': {
      id: '/(private)/(dashboard)/qa/defects/'
      path: '/qa/defects'
      fullPath: '/qa/defects/'
      preLoaderRoute: typeof privatedashboardQaDefectsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/tests/$testId/': {
      id: '/(private)/(dashboard)/qa/tests/$testId/'
      path: '/qa/tests/$testId'
      fullPath: '/qa/tests/$testId/'
      preLoaderRoute: typeof privatedashboardQaTestsTestIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/defects/$defectId/': {
      id: '/(private)/(dashboard)/qa/defects/$defectId/'
      path: '/qa/defects/$defectId'
      fullPath: '/qa/defects/$defectId/'
      preLoaderRoute: typeof privatedashboardQaDefectsDefectIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/campaigns/$campaignId/': {
      id: '/(private)/(dashboard)/qa/campaigns/$campaignId/'
      path: '/qa/campaigns/$campaignId'
      fullPath: '/qa/campaigns/$campaignId/'
      preLoaderRoute: typeof privatedashboardQaCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/qa/tests/$testId/run': {
      id: '/(private)/(dashboard)/qa/tests/$testId/run'
      path: '/qa/tests/$testId/run'
      fullPath: '/qa/tests/$testId/run'
      preLoaderRoute: typeof privatedashboardQaTestsTestIdRunRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
  }
}

interface hybridRouteRouteChildren {
  hybridUnauthorizedRoute: typeof hybridUnauthorizedRoute
}

const hybridRouteRouteChildren: hybridRouteRouteChildren = {
  hybridUnauthorizedRoute: hybridUnauthorizedRoute,
}

const hybridRouteRouteWithChildren = hybridRouteRoute._addFileChildren(
  hybridRouteRouteChildren,
)

interface privatedashboardRouteRouteChildren {
  privatedashboardDashboardIndexRoute: typeof privatedashboardDashboardIndexRoute
  privatedashboardQaIndexRoute: typeof privatedashboardQaIndexRoute
  privatedashboardQaDefectsIndexRoute: typeof privatedashboardQaDefectsIndexRoute
  privatedashboardQaEnvironmentIndexRoute: typeof privatedashboardQaEnvironmentIndexRoute
  privatedashboardQaTestsIndexRoute: typeof privatedashboardQaTestsIndexRoute
  privatedashboardQaTestsTestIdRunRoute: typeof privatedashboardQaTestsTestIdRunRoute
  privatedashboardQaCampaignsCampaignIdIndexRoute: typeof privatedashboardQaCampaignsCampaignIdIndexRoute
  privatedashboardQaDefectsDefectIdIndexRoute: typeof privatedashboardQaDefectsDefectIdIndexRoute
  privatedashboardQaTestsTestIdIndexRoute: typeof privatedashboardQaTestsTestIdIndexRoute
}

const privatedashboardRouteRouteChildren: privatedashboardRouteRouteChildren = {
  privatedashboardDashboardIndexRoute: privatedashboardDashboardIndexRoute,
  privatedashboardQaIndexRoute: privatedashboardQaIndexRoute,
  privatedashboardQaDefectsIndexRoute: privatedashboardQaDefectsIndexRoute,
  privatedashboardQaEnvironmentIndexRoute:
    privatedashboardQaEnvironmentIndexRoute,
  privatedashboardQaTestsIndexRoute: privatedashboardQaTestsIndexRoute,
  privatedashboardQaTestsTestIdRunRoute: privatedashboardQaTestsTestIdRunRoute,
  privatedashboardQaCampaignsCampaignIdIndexRoute:
    privatedashboardQaCampaignsCampaignIdIndexRoute,
  privatedashboardQaDefectsDefectIdIndexRoute:
    privatedashboardQaDefectsDefectIdIndexRoute,
  privatedashboardQaTestsTestIdIndexRoute:
    privatedashboardQaTestsTestIdIndexRoute,
}

const privatedashboardRouteRouteWithChildren =
  privatedashboardRouteRoute._addFileChildren(
    privatedashboardRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privatedashboardRouteRoute: typeof privatedashboardRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatedashboardRouteRoute: privatedashboardRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  hybridRouteRoute: hybridRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
