/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as hybridRouteRouteImport } from './routes/(hybrid)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as hybridUnauthorizedRouteImport } from './routes/(hybrid)/unauthorized'
import { Route as privatedashboardRouteRouteImport } from './routes/(private)/(dashboard)/route'
import { Route as privatedashboardDashboardIndexRouteImport } from './routes/(private)/(dashboard)/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

// ---------------------------------------------------------------------------
// Route instances
// ---------------------------------------------------------------------------

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)

const hybridRouteRoute = hybridRouteRouteImport.update({
  id: '/(hybrid)',
  getParentRoute: () => rootRouteImport,
} as any)

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)

const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)

const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)

const hybridUnauthorizedRoute = hybridUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => hybridRouteRoute,
} as any)

const privatedashboardRouteRoute = privatedashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => privateRouteRoute,
} as any)

const privatedashboardDashboardIndexRoute = privatedashboardDashboardIndexRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privatedashboardRouteRoute,
} as any)

const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

// ---------------------------------------------------------------------------
// Route tree
// ---------------------------------------------------------------------------

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/unauthorized': typeof hybridUnauthorizedRoute
  '/dashboard': typeof privatedashboardDashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/unauthorized': typeof hybridUnauthorizedRoute
  '/dashboard': typeof privatedashboardDashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRoute
  '/(private)': typeof privateRouteRoute
  '/(hybrid)': typeof hybridRouteRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(hybrid)/unauthorized': typeof hybridUnauthorizedRoute
  '/(private)/(dashboard)': typeof privatedashboardRouteRoute
  '/(private)/(dashboard)/dashboard': typeof privatedashboardDashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/forgot-password'
    | '/unauthorized'
    | '/dashboard'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/forgot-password'
    | '/unauthorized'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/(public)'
    | '/(private)'
    | '/(hybrid)'
    | '/(public)/'
    | '/(public)/login'
    | '/(public)/forgot-password'
    | '/(hybrid)/unauthorized'
    | '/(private)/(dashboard)'
    | '/(private)/(dashboard)/dashboard'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRoute
  privateRouteRoute: typeof privateRouteRoute
  hybridRouteRoute: typeof hybridRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute,
  privateRouteRoute,
  hybridRouteRoute,
  ApiAuthSplatRoute,
}

const rootRouteWithChildren = rootRouteImport._addFileChildren(rootRouteChildren)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicLoginRoute: typeof publicLoginRoute
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute,
  publicLoginRoute,
  publicForgotPasswordRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(publicRouteRouteChildren)

interface hybridRouteRouteChildren {
  hybridUnauthorizedRoute: typeof hybridUnauthorizedRoute
}

const hybridRouteRouteChildren: hybridRouteRouteChildren = {
  hybridUnauthorizedRoute,
}

const hybridRouteRouteWithChildren = hybridRouteRoute._addFileChildren(hybridRouteRouteChildren)

interface privatedashboardRouteRouteChildren {
  privatedashboardDashboardIndexRoute: typeof privatedashboardDashboardIndexRoute
}

const privatedashboardRouteRouteChildren: privatedashboardRouteRouteChildren = {
  privatedashboardDashboardIndexRoute,
}

const privatedashboardRouteRouteWithChildren = privatedashboardRouteRoute._addFileChildren(privatedashboardRouteRouteChildren)

interface privateRouteRouteChildren {
  privatedashboardRouteRoute: typeof privatedashboardRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatedashboardRouteRoute: privatedashboardRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(privateRouteRouteChildren)

export const routeTree = rootRouteWithChildren._addFileChildren({
  publicRouteRoute: publicRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  hybridRouteRoute: hybridRouteRouteWithChildren,
  ApiAuthSplatRoute,
})

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(hybrid)': {
      id: '/(hybrid)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof hybridRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hybrid)/unauthorized': {
      id: '/(hybrid)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof hybridUnauthorizedRouteImport
      parentRoute: typeof hybridRouteRoute
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)': {
      id: '/(private)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(dashboard)/dashboard': {
      id: '/(private)/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privatedashboardDashboardIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
  }
}
