/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as hybridRouteRouteImport } from './routes/(hybrid)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as hybridUnauthorizedRouteImport } from './routes/(hybrid)/unauthorized'
import { Route as privatedashboardRouteRouteImport } from './routes/(private)/(dashboard)/route'
import { Route as publicRegisterIndexRouteImport } from './routes/(public)/register/index'
import { Route as privateTasksIndexRouteImport } from './routes/(private)/tasks/index'
import { Route as privatePosIndexRouteImport } from './routes/(private)/pos/index'
import { Route as privateOrdersIndexRouteImport } from './routes/(private)/orders/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicRegisterBusinessSetupRouteImport } from './routes/(public)/register/business-setup'
import { Route as privatedashboardNotificationsRouteImport } from './routes/(private)/(dashboard)/notifications'
import { Route as privatedashboardDashboardRouteImport } from './routes/(private)/(dashboard)/dashboard'
import { Route as privatedashboardContactUsRouteImport } from './routes/(private)/(dashboard)/contact-us'
import { Route as privatedashboardSettingsRouteRouteImport } from './routes/(private)/(dashboard)/settings/route'
import { Route as privatedashboardPreparationRouteRouteImport } from './routes/(private)/(dashboard)/preparation/route'
import { Route as privatedashboardBusinessRouteRouteImport } from './routes/(private)/(dashboard)/business/route'
import { Route as privatedashboardBillingRouteRouteImport } from './routes/(private)/(dashboard)/billing/route'
import { Route as privatedashboardAccountRouteRouteImport } from './routes/(private)/(dashboard)/account/route'
import { Route as ApiCronHourlyIndexRouteImport } from './routes/api/cron/hourly/index'
import { Route as ApiCronDailyIndexRouteImport } from './routes/api/cron/daily/index'
import { Route as ApiBillingWebhookIndexRouteImport } from './routes/api/billing/webhook/index'
import { Route as privateTasksCreateIndexRouteImport } from './routes/(private)/tasks/create/index'
import { Route as privateTasksTaskIdIndexRouteImport } from './routes/(private)/tasks/$taskId/index'
import { Route as privatedashboardTransactionsIndexRouteImport } from './routes/(private)/(dashboard)/transactions/index'
import { Route as privatedashboardSettingsIndexRouteImport } from './routes/(private)/(dashboard)/settings/index'
import { Route as privatedashboardSalesReportsIndexRouteImport } from './routes/(private)/(dashboard)/sales-reports/index'
import { Route as privatedashboardPurchasesIndexRouteImport } from './routes/(private)/(dashboard)/purchases/index'
import { Route as privatedashboardProductsIndexRouteImport } from './routes/(private)/(dashboard)/products/index'
import { Route as privatedashboardPreparationIndexRouteImport } from './routes/(private)/(dashboard)/preparation/index'
import { Route as privatedashboardOrderHistoryIndexRouteImport } from './routes/(private)/(dashboard)/order-history/index'
import { Route as privatedashboardInventoryReportsIndexRouteImport } from './routes/(private)/(dashboard)/inventory-reports/index'
import { Route as privatedashboardIngredientsIndexRouteImport } from './routes/(private)/(dashboard)/ingredients/index'
import { Route as privatedashboardEmployeesIndexRouteImport } from './routes/(private)/(dashboard)/employees/index'
import { Route as privatedashboardBusinessIndexRouteImport } from './routes/(private)/(dashboard)/business/index'
import { Route as privatedashboardBillingIndexRouteImport } from './routes/(private)/(dashboard)/billing/index'
import { Route as privatedashboardAccountIndexRouteImport } from './routes/(private)/(dashboard)/account/index'
import { Route as ApiBillingWebhookStripeRouteImport } from './routes/api/billing/webhook/stripe'
import { Route as privatedashboardSettingsComplianceRouteImport } from './routes/(private)/(dashboard)/settings/compliance'
import { Route as privatedashboardPreparationHistoryRouteImport } from './routes/(private)/(dashboard)/preparation/history'
import { Route as privatedashboardBillingManualPaymentRouteImport } from './routes/(private)/(dashboard)/billing/manual-payment'
import { Route as privatedashboardBusinessSuppliersRouteRouteImport } from './routes/(private)/(dashboard)/business/suppliers/route'
import { Route as privatedashboardBusinessSubscriptionRouteRouteImport } from './routes/(private)/(dashboard)/business/subscription/route'
import { Route as privatedashboardBusinessCustomersRouteRouteImport } from './routes/(private)/(dashboard)/business/customers/route'
import { Route as privatedashboardTransactionsTransactionIdIndexRouteImport } from './routes/(private)/(dashboard)/transactions/$transactionId/index'
import { Route as privatedashboardPurchasesPurchaseIdIndexRouteImport } from './routes/(private)/(dashboard)/purchases/$purchaseId/index'
import { Route as privatedashboardProductsCreateIndexRouteImport } from './routes/(private)/(dashboard)/products/create/index'
import { Route as privatedashboardProductsProductIdIndexRouteImport } from './routes/(private)/(dashboard)/products/$productId/index'
import { Route as privatedashboardOrderHistoryOrderIdIndexRouteImport } from './routes/(private)/(dashboard)/order-history/$orderId/index'
import { Route as privatedashboardIngredientsCreateIndexRouteImport } from './routes/(private)/(dashboard)/ingredients/create/index'
import { Route as privatedashboardIngredientsIngredientIdIndexRouteImport } from './routes/(private)/(dashboard)/ingredients/$ingredientId/index'
import { Route as privatedashboardEmployeesCreateIndexRouteImport } from './routes/(private)/(dashboard)/employees/create/index'
import { Route as privatedashboardEmployeesEmployeeIdIndexRouteImport } from './routes/(private)/(dashboard)/employees/$employeeId/index'
import { Route as privatedashboardBusinessSuppliersIndexRouteImport } from './routes/(private)/(dashboard)/business/suppliers/index'
import { Route as privatedashboardBusinessSubscriptionIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/index'
import { Route as privatedashboardBusinessProfileIndexRouteImport } from './routes/(private)/(dashboard)/business/profile/index'
import { Route as privatedashboardBusinessPermissionsIndexRouteImport } from './routes/(private)/(dashboard)/business/permissions/index'
import { Route as privatedashboardBusinessCustomersIndexRouteImport } from './routes/(private)/(dashboard)/business/customers/index'
import { Route as privatedashboardBusinessCapabilitiesIndexRouteImport } from './routes/(private)/(dashboard)/business/capabilities/index'
import { Route as privatedashboardBusinessBranchesIndexRouteImport } from './routes/(private)/(dashboard)/business/branches/index'
import { Route as privatedashboardAccountSecurityIndexRouteImport } from './routes/(private)/(dashboard)/account/security/index'
import { Route as privatedashboardAccountPreferencesIndexRouteImport } from './routes/(private)/(dashboard)/account/preferences/index'
import { Route as privatedashboardBusinessSubscriptionPaymentMethodsRouteImport } from './routes/(private)/(dashboard)/business/subscription/payment-methods'
import { Route as privatedashboardBusinessSubscriptionSuccessIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/success/index'
import { Route as privatedashboardBusinessSubscriptionReactivateIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/reactivate/index'
import { Route as privatedashboardBusinessSubscriptionQuotesIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/quotes/index'
import { Route as privatedashboardBusinessSubscriptionPricingIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/pricing/index'
import { Route as privatedashboardBusinessSubscriptionPlansIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/plans/index'
import { Route as privatedashboardBusinessSubscriptionInvoicesIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/invoices/index'
import { Route as privatedashboardBusinessSubscriptionCreditsIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/credits/index'
import { Route as privatedashboardBusinessSubscriptionCheckoutIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/checkout/index'
import { Route as privatedashboardBusinessPermissionsAuditIndexRouteImport } from './routes/(private)/(dashboard)/business/permissions/audit/index'
import { Route as privatedashboardBillingCreditsCheckoutIndexRouteImport } from './routes/(private)/(dashboard)/billing/credits/checkout/index'
import { Route as privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/quotes/$quoteId/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const hybridRouteRoute = hybridRouteRouteImport.update({
  id: '/(hybrid)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const hybridUnauthorizedRoute = hybridUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => hybridRouteRoute,
} as any)
const privatedashboardRouteRoute = privatedashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicRegisterIndexRoute = publicRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateTasksIndexRoute = privateTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePosIndexRoute = privatePosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateOrdersIndexRoute = privateOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterBusinessSetupRoute =
  publicRegisterBusinessSetupRouteImport.update({
    id: '/register/business-setup',
    path: '/register/business-setup',
    getParentRoute: () => publicRouteRoute,
  } as any)
const privatedashboardNotificationsRoute =
  privatedashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardDashboardRoute =
  privatedashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardContactUsRoute =
  privatedashboardContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardSettingsRouteRoute =
  privatedashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardPreparationRouteRoute =
  privatedashboardPreparationRouteRouteImport.update({
    id: '/preparation',
    path: '/preparation',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardBusinessRouteRoute =
  privatedashboardBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardBillingRouteRoute =
  privatedashboardBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardAccountRouteRoute =
  privatedashboardAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const ApiCronHourlyIndexRoute = ApiCronHourlyIndexRouteImport.update({
  id: '/api/cron/hourly/',
  path: '/api/cron/hourly/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyIndexRoute = ApiCronDailyIndexRouteImport.update({
  id: '/api/cron/daily/',
  path: '/api/cron/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookIndexRoute = ApiBillingWebhookIndexRouteImport.update({
  id: '/api/billing/webhook/',
  path: '/api/billing/webhook/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateTasksCreateIndexRoute = privateTasksCreateIndexRouteImport.update({
  id: '/tasks/create/',
  path: '/tasks/create/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateTasksTaskIdIndexRoute = privateTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatedashboardTransactionsIndexRoute =
  privatedashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardSettingsIndexRoute =
  privatedashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardSettingsRouteRoute,
  } as any)
const privatedashboardSalesReportsIndexRoute =
  privatedashboardSalesReportsIndexRouteImport.update({
    id: '/sales-reports/',
    path: '/sales-reports/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardPurchasesIndexRoute =
  privatedashboardPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardProductsIndexRoute =
  privatedashboardProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardPreparationIndexRoute =
  privatedashboardPreparationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardPreparationRouteRoute,
  } as any)
const privatedashboardOrderHistoryIndexRoute =
  privatedashboardOrderHistoryIndexRouteImport.update({
    id: '/order-history/',
    path: '/order-history/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardInventoryReportsIndexRoute =
  privatedashboardInventoryReportsIndexRouteImport.update({
    id: '/inventory-reports/',
    path: '/inventory-reports/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardIngredientsIndexRoute =
  privatedashboardIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardEmployeesIndexRoute =
  privatedashboardEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardBusinessIndexRoute =
  privatedashboardBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBillingIndexRoute =
  privatedashboardBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBillingRouteRoute,
  } as any)
const privatedashboardAccountIndexRoute =
  privatedashboardAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardAccountRouteRoute,
  } as any)
const ApiBillingWebhookStripeRoute = ApiBillingWebhookStripeRouteImport.update({
  id: '/api/billing/webhook/stripe',
  path: '/api/billing/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const privatedashboardSettingsComplianceRoute =
  privatedashboardSettingsComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => privatedashboardSettingsRouteRoute,
  } as any)
const privatedashboardPreparationHistoryRoute =
  privatedashboardPreparationHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => privatedashboardPreparationRouteRoute,
  } as any)
const privatedashboardBillingManualPaymentRoute =
  privatedashboardBillingManualPaymentRouteImport.update({
    id: '/manual-payment',
    path: '/manual-payment',
    getParentRoute: () => privatedashboardBillingRouteRoute,
  } as any)
const privatedashboardBusinessSuppliersRouteRoute =
  privatedashboardBusinessSuppliersRouteRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionRouteRoute =
  privatedashboardBusinessSubscriptionRouteRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessCustomersRouteRoute =
  privatedashboardBusinessCustomersRouteRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardTransactionsTransactionIdIndexRoute =
  privatedashboardTransactionsTransactionIdIndexRouteImport.update({
    id: '/transactions/$transactionId/',
    path: '/transactions/$transactionId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardPurchasesPurchaseIdIndexRoute =
  privatedashboardPurchasesPurchaseIdIndexRouteImport.update({
    id: '/purchases/$purchaseId/',
    path: '/purchases/$purchaseId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardProductsCreateIndexRoute =
  privatedashboardProductsCreateIndexRouteImport.update({
    id: '/products/create/',
    path: '/products/create/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardProductsProductIdIndexRoute =
  privatedashboardProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardOrderHistoryOrderIdIndexRoute =
  privatedashboardOrderHistoryOrderIdIndexRouteImport.update({
    id: '/order-history/$orderId/',
    path: '/order-history/$orderId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardIngredientsCreateIndexRoute =
  privatedashboardIngredientsCreateIndexRouteImport.update({
    id: '/ingredients/create/',
    path: '/ingredients/create/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardIngredientsIngredientIdIndexRoute =
  privatedashboardIngredientsIngredientIdIndexRouteImport.update({
    id: '/ingredients/$ingredientId/',
    path: '/ingredients/$ingredientId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardEmployeesCreateIndexRoute =
  privatedashboardEmployeesCreateIndexRouteImport.update({
    id: '/employees/create/',
    path: '/employees/create/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardEmployeesEmployeeIdIndexRoute =
  privatedashboardEmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardBusinessSuppliersIndexRoute =
  privatedashboardBusinessSuppliersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessSuppliersRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionIndexRoute =
  privatedashboardBusinessSubscriptionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessProfileIndexRoute =
  privatedashboardBusinessProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessPermissionsIndexRoute =
  privatedashboardBusinessPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessCustomersIndexRoute =
  privatedashboardBusinessCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessCustomersRouteRoute,
  } as any)
const privatedashboardBusinessCapabilitiesIndexRoute =
  privatedashboardBusinessCapabilitiesIndexRouteImport.update({
    id: '/capabilities/',
    path: '/capabilities/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessBranchesIndexRoute =
  privatedashboardBusinessBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardAccountSecurityIndexRoute =
  privatedashboardAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => privatedashboardAccountRouteRoute,
  } as any)
const privatedashboardAccountPreferencesIndexRoute =
  privatedashboardAccountPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => privatedashboardAccountRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionPaymentMethodsRoute =
  privatedashboardBusinessSubscriptionPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionSuccessIndexRoute =
  privatedashboardBusinessSubscriptionSuccessIndexRouteImport.update({
    id: '/success/',
    path: '/success/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionReactivateIndexRoute =
  privatedashboardBusinessSubscriptionReactivateIndexRouteImport.update({
    id: '/reactivate/',
    path: '/reactivate/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionQuotesIndexRoute =
  privatedashboardBusinessSubscriptionQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionPricingIndexRoute =
  privatedashboardBusinessSubscriptionPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionPlansIndexRoute =
  privatedashboardBusinessSubscriptionPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionInvoicesIndexRoute =
  privatedashboardBusinessSubscriptionInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionCreditsIndexRoute =
  privatedashboardBusinessSubscriptionCreditsIndexRouteImport.update({
    id: '/credits/',
    path: '/credits/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionCheckoutIndexRoute =
  privatedashboardBusinessSubscriptionCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessPermissionsAuditIndexRoute =
  privatedashboardBusinessPermissionsAuditIndexRouteImport.update({
    id: '/permissions/audit/',
    path: '/permissions/audit/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBillingCreditsCheckoutIndexRoute =
  privatedashboardBillingCreditsCheckoutIndexRouteImport.update({
    id: '/credits/checkout/',
    path: '/credits/checkout/',
    getParentRoute: () => privatedashboardBillingRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute =
  privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRouteImport.update({
    id: '/quotes/$quoteId/',
    path: '/quotes/$quoteId/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/unauthorized': typeof hybridUnauthorizedRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/account': typeof privatedashboardAccountRouteRouteWithChildren
  '/billing': typeof privatedashboardBillingRouteRouteWithChildren
  '/business': typeof privatedashboardBusinessRouteRouteWithChildren
  '/preparation': typeof privatedashboardPreparationRouteRouteWithChildren
  '/settings': typeof privatedashboardSettingsRouteRouteWithChildren
  '/contact-us': typeof privatedashboardContactUsRoute
  '/dashboard': typeof privatedashboardDashboardRoute
  '/notifications': typeof privatedashboardNotificationsRoute
  '/register/business-setup': typeof publicRegisterBusinessSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders/': typeof privateOrdersIndexRoute
  '/pos/': typeof privatePosIndexRoute
  '/tasks/': typeof privateTasksIndexRoute
  '/register/': typeof publicRegisterIndexRoute
  '/business/customers': typeof privatedashboardBusinessCustomersRouteRouteWithChildren
  '/business/subscription': typeof privatedashboardBusinessSubscriptionRouteRouteWithChildren
  '/business/suppliers': typeof privatedashboardBusinessSuppliersRouteRouteWithChildren
  '/billing/manual-payment': typeof privatedashboardBillingManualPaymentRoute
  '/preparation/history': typeof privatedashboardPreparationHistoryRoute
  '/settings/compliance': typeof privatedashboardSettingsComplianceRoute
  '/api/billing/webhook/stripe': typeof ApiBillingWebhookStripeRoute
  '/account/': typeof privatedashboardAccountIndexRoute
  '/billing/': typeof privatedashboardBillingIndexRoute
  '/business/': typeof privatedashboardBusinessIndexRoute
  '/employees/': typeof privatedashboardEmployeesIndexRoute
  '/ingredients/': typeof privatedashboardIngredientsIndexRoute
  '/inventory-reports/': typeof privatedashboardInventoryReportsIndexRoute
  '/order-history/': typeof privatedashboardOrderHistoryIndexRoute
  '/preparation/': typeof privatedashboardPreparationIndexRoute
  '/products/': typeof privatedashboardProductsIndexRoute
  '/purchases/': typeof privatedashboardPurchasesIndexRoute
  '/sales-reports/': typeof privatedashboardSalesReportsIndexRoute
  '/settings/': typeof privatedashboardSettingsIndexRoute
  '/transactions/': typeof privatedashboardTransactionsIndexRoute
  '/tasks/$taskId/': typeof privateTasksTaskIdIndexRoute
  '/tasks/create/': typeof privateTasksCreateIndexRoute
  '/api/billing/webhook/': typeof ApiBillingWebhookIndexRoute
  '/api/cron/daily/': typeof ApiCronDailyIndexRoute
  '/api/cron/hourly/': typeof ApiCronHourlyIndexRoute
  '/business/subscription/payment-methods': typeof privatedashboardBusinessSubscriptionPaymentMethodsRoute
  '/account/preferences/': typeof privatedashboardAccountPreferencesIndexRoute
  '/account/security/': typeof privatedashboardAccountSecurityIndexRoute
  '/business/branches/': typeof privatedashboardBusinessBranchesIndexRoute
  '/business/capabilities/': typeof privatedashboardBusinessCapabilitiesIndexRoute
  '/business/customers/': typeof privatedashboardBusinessCustomersIndexRoute
  '/business/permissions/': typeof privatedashboardBusinessPermissionsIndexRoute
  '/business/profile/': typeof privatedashboardBusinessProfileIndexRoute
  '/business/subscription/': typeof privatedashboardBusinessSubscriptionIndexRoute
  '/business/suppliers/': typeof privatedashboardBusinessSuppliersIndexRoute
  '/employees/$employeeId/': typeof privatedashboardEmployeesEmployeeIdIndexRoute
  '/employees/create/': typeof privatedashboardEmployeesCreateIndexRoute
  '/ingredients/$ingredientId/': typeof privatedashboardIngredientsIngredientIdIndexRoute
  '/ingredients/create/': typeof privatedashboardIngredientsCreateIndexRoute
  '/order-history/$orderId/': typeof privatedashboardOrderHistoryOrderIdIndexRoute
  '/products/$productId/': typeof privatedashboardProductsProductIdIndexRoute
  '/products/create/': typeof privatedashboardProductsCreateIndexRoute
  '/purchases/$purchaseId/': typeof privatedashboardPurchasesPurchaseIdIndexRoute
  '/transactions/$transactionId/': typeof privatedashboardTransactionsTransactionIdIndexRoute
  '/billing/credits/checkout/': typeof privatedashboardBillingCreditsCheckoutIndexRoute
  '/business/permissions/audit/': typeof privatedashboardBusinessPermissionsAuditIndexRoute
  '/business/subscription/checkout/': typeof privatedashboardBusinessSubscriptionCheckoutIndexRoute
  '/business/subscription/credits/': typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  '/business/subscription/invoices/': typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  '/business/subscription/plans/': typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  '/business/subscription/pricing/': typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  '/business/subscription/quotes/': typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  '/business/subscription/reactivate/': typeof privatedashboardBusinessSubscriptionReactivateIndexRoute
  '/business/subscription/success/': typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  '/business/subscription/quotes/$quoteId/': typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof hybridUnauthorizedRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/contact-us': typeof privatedashboardContactUsRoute
  '/dashboard': typeof privatedashboardDashboardRoute
  '/notifications': typeof privatedashboardNotificationsRoute
  '/register/business-setup': typeof publicRegisterBusinessSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders': typeof privateOrdersIndexRoute
  '/pos': typeof privatePosIndexRoute
  '/tasks': typeof privateTasksIndexRoute
  '/register': typeof publicRegisterIndexRoute
  '/billing/manual-payment': typeof privatedashboardBillingManualPaymentRoute
  '/preparation/history': typeof privatedashboardPreparationHistoryRoute
  '/settings/compliance': typeof privatedashboardSettingsComplianceRoute
  '/api/billing/webhook/stripe': typeof ApiBillingWebhookStripeRoute
  '/account': typeof privatedashboardAccountIndexRoute
  '/billing': typeof privatedashboardBillingIndexRoute
  '/business': typeof privatedashboardBusinessIndexRoute
  '/employees': typeof privatedashboardEmployeesIndexRoute
  '/ingredients': typeof privatedashboardIngredientsIndexRoute
  '/inventory-reports': typeof privatedashboardInventoryReportsIndexRoute
  '/order-history': typeof privatedashboardOrderHistoryIndexRoute
  '/preparation': typeof privatedashboardPreparationIndexRoute
  '/products': typeof privatedashboardProductsIndexRoute
  '/purchases': typeof privatedashboardPurchasesIndexRoute
  '/sales-reports': typeof privatedashboardSalesReportsIndexRoute
  '/settings': typeof privatedashboardSettingsIndexRoute
  '/transactions': typeof privatedashboardTransactionsIndexRoute
  '/tasks/$taskId': typeof privateTasksTaskIdIndexRoute
  '/tasks/create': typeof privateTasksCreateIndexRoute
  '/api/billing/webhook': typeof ApiBillingWebhookIndexRoute
  '/api/cron/daily': typeof ApiCronDailyIndexRoute
  '/api/cron/hourly': typeof ApiCronHourlyIndexRoute
  '/business/subscription/payment-methods': typeof privatedashboardBusinessSubscriptionPaymentMethodsRoute
  '/account/preferences': typeof privatedashboardAccountPreferencesIndexRoute
  '/account/security': typeof privatedashboardAccountSecurityIndexRoute
  '/business/branches': typeof privatedashboardBusinessBranchesIndexRoute
  '/business/capabilities': typeof privatedashboardBusinessCapabilitiesIndexRoute
  '/business/customers': typeof privatedashboardBusinessCustomersIndexRoute
  '/business/permissions': typeof privatedashboardBusinessPermissionsIndexRoute
  '/business/profile': typeof privatedashboardBusinessProfileIndexRoute
  '/business/subscription': typeof privatedashboardBusinessSubscriptionIndexRoute
  '/business/suppliers': typeof privatedashboardBusinessSuppliersIndexRoute
  '/employees/$employeeId': typeof privatedashboardEmployeesEmployeeIdIndexRoute
  '/employees/create': typeof privatedashboardEmployeesCreateIndexRoute
  '/ingredients/$ingredientId': typeof privatedashboardIngredientsIngredientIdIndexRoute
  '/ingredients/create': typeof privatedashboardIngredientsCreateIndexRoute
  '/order-history/$orderId': typeof privatedashboardOrderHistoryOrderIdIndexRoute
  '/products/$productId': typeof privatedashboardProductsProductIdIndexRoute
  '/products/create': typeof privatedashboardProductsCreateIndexRoute
  '/purchases/$purchaseId': typeof privatedashboardPurchasesPurchaseIdIndexRoute
  '/transactions/$transactionId': typeof privatedashboardTransactionsTransactionIdIndexRoute
  '/billing/credits/checkout': typeof privatedashboardBillingCreditsCheckoutIndexRoute
  '/business/permissions/audit': typeof privatedashboardBusinessPermissionsAuditIndexRoute
  '/business/subscription/checkout': typeof privatedashboardBusinessSubscriptionCheckoutIndexRoute
  '/business/subscription/credits': typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  '/business/subscription/invoices': typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  '/business/subscription/plans': typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  '/business/subscription/pricing': typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  '/business/subscription/quotes': typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  '/business/subscription/reactivate': typeof privatedashboardBusinessSubscriptionReactivateIndexRoute
  '/business/subscription/success': typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  '/business/subscription/quotes/$quoteId': typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(hybrid)': typeof hybridRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/(dashboard)': typeof privatedashboardRouteRouteWithChildren
  '/(hybrid)/unauthorized': typeof hybridUnauthorizedRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/(dashboard)/account': typeof privatedashboardAccountRouteRouteWithChildren
  '/(private)/(dashboard)/billing': typeof privatedashboardBillingRouteRouteWithChildren
  '/(private)/(dashboard)/business': typeof privatedashboardBusinessRouteRouteWithChildren
  '/(private)/(dashboard)/preparation': typeof privatedashboardPreparationRouteRouteWithChildren
  '/(private)/(dashboard)/settings': typeof privatedashboardSettingsRouteRouteWithChildren
  '/(private)/(dashboard)/contact-us': typeof privatedashboardContactUsRoute
  '/(private)/(dashboard)/dashboard': typeof privatedashboardDashboardRoute
  '/(private)/(dashboard)/notifications': typeof privatedashboardNotificationsRoute
  '/(public)/register/business-setup': typeof publicRegisterBusinessSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(private)/orders/': typeof privateOrdersIndexRoute
  '/(private)/pos/': typeof privatePosIndexRoute
  '/(private)/tasks/': typeof privateTasksIndexRoute
  '/(public)/register/': typeof publicRegisterIndexRoute
  '/(private)/(dashboard)/business/customers': typeof privatedashboardBusinessCustomersRouteRouteWithChildren
  '/(private)/(dashboard)/business/subscription': typeof privatedashboardBusinessSubscriptionRouteRouteWithChildren
  '/(private)/(dashboard)/business/suppliers': typeof privatedashboardBusinessSuppliersRouteRouteWithChildren
  '/(private)/(dashboard)/billing/manual-payment': typeof privatedashboardBillingManualPaymentRoute
  '/(private)/(dashboard)/preparation/history': typeof privatedashboardPreparationHistoryRoute
  '/(private)/(dashboard)/settings/compliance': typeof privatedashboardSettingsComplianceRoute
  '/api/billing/webhook/stripe': typeof ApiBillingWebhookStripeRoute
  '/(private)/(dashboard)/account/': typeof privatedashboardAccountIndexRoute
  '/(private)/(dashboard)/billing/': typeof privatedashboardBillingIndexRoute
  '/(private)/(dashboard)/business/': typeof privatedashboardBusinessIndexRoute
  '/(private)/(dashboard)/employees/': typeof privatedashboardEmployeesIndexRoute
  '/(private)/(dashboard)/ingredients/': typeof privatedashboardIngredientsIndexRoute
  '/(private)/(dashboard)/inventory-reports/': typeof privatedashboardInventoryReportsIndexRoute
  '/(private)/(dashboard)/order-history/': typeof privatedashboardOrderHistoryIndexRoute
  '/(private)/(dashboard)/preparation/': typeof privatedashboardPreparationIndexRoute
  '/(private)/(dashboard)/products/': typeof privatedashboardProductsIndexRoute
  '/(private)/(dashboard)/purchases/': typeof privatedashboardPurchasesIndexRoute
  '/(private)/(dashboard)/sales-reports/': typeof privatedashboardSalesReportsIndexRoute
  '/(private)/(dashboard)/settings/': typeof privatedashboardSettingsIndexRoute
  '/(private)/(dashboard)/transactions/': typeof privatedashboardTransactionsIndexRoute
  '/(private)/tasks/$taskId/': typeof privateTasksTaskIdIndexRoute
  '/(private)/tasks/create/': typeof privateTasksCreateIndexRoute
  '/api/billing/webhook/': typeof ApiBillingWebhookIndexRoute
  '/api/cron/daily/': typeof ApiCronDailyIndexRoute
  '/api/cron/hourly/': typeof ApiCronHourlyIndexRoute
  '/(private)/(dashboard)/business/subscription/payment-methods': typeof privatedashboardBusinessSubscriptionPaymentMethodsRoute
  '/(private)/(dashboard)/account/preferences/': typeof privatedashboardAccountPreferencesIndexRoute
  '/(private)/(dashboard)/account/security/': typeof privatedashboardAccountSecurityIndexRoute
  '/(private)/(dashboard)/business/branches/': typeof privatedashboardBusinessBranchesIndexRoute
  '/(private)/(dashboard)/business/capabilities/': typeof privatedashboardBusinessCapabilitiesIndexRoute
  '/(private)/(dashboard)/business/customers/': typeof privatedashboardBusinessCustomersIndexRoute
  '/(private)/(dashboard)/business/permissions/': typeof privatedashboardBusinessPermissionsIndexRoute
  '/(private)/(dashboard)/business/profile/': typeof privatedashboardBusinessProfileIndexRoute
  '/(private)/(dashboard)/business/subscription/': typeof privatedashboardBusinessSubscriptionIndexRoute
  '/(private)/(dashboard)/business/suppliers/': typeof privatedashboardBusinessSuppliersIndexRoute
  '/(private)/(dashboard)/employees/$employeeId/': typeof privatedashboardEmployeesEmployeeIdIndexRoute
  '/(private)/(dashboard)/employees/create/': typeof privatedashboardEmployeesCreateIndexRoute
  '/(private)/(dashboard)/ingredients/$ingredientId/': typeof privatedashboardIngredientsIngredientIdIndexRoute
  '/(private)/(dashboard)/ingredients/create/': typeof privatedashboardIngredientsCreateIndexRoute
  '/(private)/(dashboard)/order-history/$orderId/': typeof privatedashboardOrderHistoryOrderIdIndexRoute
  '/(private)/(dashboard)/products/$productId/': typeof privatedashboardProductsProductIdIndexRoute
  '/(private)/(dashboard)/products/create/': typeof privatedashboardProductsCreateIndexRoute
  '/(private)/(dashboard)/purchases/$purchaseId/': typeof privatedashboardPurchasesPurchaseIdIndexRoute
  '/(private)/(dashboard)/transactions/$transactionId/': typeof privatedashboardTransactionsTransactionIdIndexRoute
  '/(private)/(dashboard)/billing/credits/checkout/': typeof privatedashboardBillingCreditsCheckoutIndexRoute
  '/(private)/(dashboard)/business/permissions/audit/': typeof privatedashboardBusinessPermissionsAuditIndexRoute
  '/(private)/(dashboard)/business/subscription/checkout/': typeof privatedashboardBusinessSubscriptionCheckoutIndexRoute
  '/(private)/(dashboard)/business/subscription/credits/': typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  '/(private)/(dashboard)/business/subscription/invoices/': typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  '/(private)/(dashboard)/business/subscription/plans/': typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  '/(private)/(dashboard)/business/subscription/pricing/': typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  '/(private)/(dashboard)/business/subscription/quotes/': typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  '/(private)/(dashboard)/business/subscription/reactivate/': typeof privatedashboardBusinessSubscriptionReactivateIndexRoute
  '/(private)/(dashboard)/business/subscription/success/': typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  '/(private)/(dashboard)/business/subscription/quotes/$quoteId/': typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/account'
    | '/billing'
    | '/business'
    | '/preparation'
    | '/settings'
    | '/contact-us'
    | '/dashboard'
    | '/notifications'
    | '/register/business-setup'
    | '/api/auth/$'
    | '/orders/'
    | '/pos/'
    | '/tasks/'
    | '/register/'
    | '/business/customers'
    | '/business/subscription'
    | '/business/suppliers'
    | '/billing/manual-payment'
    | '/preparation/history'
    | '/settings/compliance'
    | '/api/billing/webhook/stripe'
    | '/account/'
    | '/billing/'
    | '/business/'
    | '/employees/'
    | '/ingredients/'
    | '/inventory-reports/'
    | '/order-history/'
    | '/preparation/'
    | '/products/'
    | '/purchases/'
    | '/sales-reports/'
    | '/settings/'
    | '/transactions/'
    | '/tasks/$taskId/'
    | '/tasks/create/'
    | '/api/billing/webhook/'
    | '/api/cron/daily/'
    | '/api/cron/hourly/'
    | '/business/subscription/payment-methods'
    | '/account/preferences/'
    | '/account/security/'
    | '/business/branches/'
    | '/business/capabilities/'
    | '/business/customers/'
    | '/business/permissions/'
    | '/business/profile/'
    | '/business/subscription/'
    | '/business/suppliers/'
    | '/employees/$employeeId/'
    | '/employees/create/'
    | '/ingredients/$ingredientId/'
    | '/ingredients/create/'
    | '/order-history/$orderId/'
    | '/products/$productId/'
    | '/products/create/'
    | '/purchases/$purchaseId/'
    | '/transactions/$transactionId/'
    | '/billing/credits/checkout/'
    | '/business/permissions/audit/'
    | '/business/subscription/checkout/'
    | '/business/subscription/credits/'
    | '/business/subscription/invoices/'
    | '/business/subscription/plans/'
    | '/business/subscription/pricing/'
    | '/business/subscription/quotes/'
    | '/business/subscription/reactivate/'
    | '/business/subscription/success/'
    | '/business/subscription/quotes/$quoteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/contact-us'
    | '/dashboard'
    | '/notifications'
    | '/register/business-setup'
    | '/api/auth/$'
    | '/orders'
    | '/pos'
    | '/tasks'
    | '/register'
    | '/billing/manual-payment'
    | '/preparation/history'
    | '/settings/compliance'
    | '/api/billing/webhook/stripe'
    | '/account'
    | '/billing'
    | '/business'
    | '/employees'
    | '/ingredients'
    | '/inventory-reports'
    | '/order-history'
    | '/preparation'
    | '/products'
    | '/purchases'
    | '/sales-reports'
    | '/settings'
    | '/transactions'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/api/billing/webhook'
    | '/api/cron/daily'
    | '/api/cron/hourly'
    | '/business/subscription/payment-methods'
    | '/account/preferences'
    | '/account/security'
    | '/business/branches'
    | '/business/capabilities'
    | '/business/customers'
    | '/business/permissions'
    | '/business/profile'
    | '/business/subscription'
    | '/business/suppliers'
    | '/employees/$employeeId'
    | '/employees/create'
    | '/ingredients/$ingredientId'
    | '/ingredients/create'
    | '/order-history/$orderId'
    | '/products/$productId'
    | '/products/create'
    | '/purchases/$purchaseId'
    | '/transactions/$transactionId'
    | '/billing/credits/checkout'
    | '/business/permissions/audit'
    | '/business/subscription/checkout'
    | '/business/subscription/credits'
    | '/business/subscription/invoices'
    | '/business/subscription/plans'
    | '/business/subscription/pricing'
    | '/business/subscription/quotes'
    | '/business/subscription/reactivate'
    | '/business/subscription/success'
    | '/business/subscription/quotes/$quoteId'
  id:
    | '__root__'
    | '/(hybrid)'
    | '/(private)'
    | '/(public)'
    | '/(private)/(dashboard)'
    | '/(hybrid)/unauthorized'
    | '/(public)/forgot-password'
    | '/(public)/login'
    | '/(public)/'
    | '/(private)/(dashboard)/account'
    | '/(private)/(dashboard)/billing'
    | '/(private)/(dashboard)/business'
    | '/(private)/(dashboard)/preparation'
    | '/(private)/(dashboard)/settings'
    | '/(private)/(dashboard)/contact-us'
    | '/(private)/(dashboard)/dashboard'
    | '/(private)/(dashboard)/notifications'
    | '/(public)/register/business-setup'
    | '/api/auth/$'
    | '/(private)/orders/'
    | '/(private)/pos/'
    | '/(private)/tasks/'
    | '/(public)/register/'
    | '/(private)/(dashboard)/business/customers'
    | '/(private)/(dashboard)/business/subscription'
    | '/(private)/(dashboard)/business/suppliers'
    | '/(private)/(dashboard)/billing/manual-payment'
    | '/(private)/(dashboard)/preparation/history'
    | '/(private)/(dashboard)/settings/compliance'
    | '/api/billing/webhook/stripe'
    | '/(private)/(dashboard)/account/'
    | '/(private)/(dashboard)/billing/'
    | '/(private)/(dashboard)/business/'
    | '/(private)/(dashboard)/employees/'
    | '/(private)/(dashboard)/ingredients/'
    | '/(private)/(dashboard)/inventory-reports/'
    | '/(private)/(dashboard)/order-history/'
    | '/(private)/(dashboard)/preparation/'
    | '/(private)/(dashboard)/products/'
    | '/(private)/(dashboard)/purchases/'
    | '/(private)/(dashboard)/sales-reports/'
    | '/(private)/(dashboard)/settings/'
    | '/(private)/(dashboard)/transactions/'
    | '/(private)/tasks/$taskId/'
    | '/(private)/tasks/create/'
    | '/api/billing/webhook/'
    | '/api/cron/daily/'
    | '/api/cron/hourly/'
    | '/(private)/(dashboard)/business/subscription/payment-methods'
    | '/(private)/(dashboard)/account/preferences/'
    | '/(private)/(dashboard)/account/security/'
    | '/(private)/(dashboard)/business/branches/'
    | '/(private)/(dashboard)/business/capabilities/'
    | '/(private)/(dashboard)/business/customers/'
    | '/(private)/(dashboard)/business/permissions/'
    | '/(private)/(dashboard)/business/profile/'
    | '/(private)/(dashboard)/business/subscription/'
    | '/(private)/(dashboard)/business/suppliers/'
    | '/(private)/(dashboard)/employees/$employeeId/'
    | '/(private)/(dashboard)/employees/create/'
    | '/(private)/(dashboard)/ingredients/$ingredientId/'
    | '/(private)/(dashboard)/ingredients/create/'
    | '/(private)/(dashboard)/order-history/$orderId/'
    | '/(private)/(dashboard)/products/$productId/'
    | '/(private)/(dashboard)/products/create/'
    | '/(private)/(dashboard)/purchases/$purchaseId/'
    | '/(private)/(dashboard)/transactions/$transactionId/'
    | '/(private)/(dashboard)/billing/credits/checkout/'
    | '/(private)/(dashboard)/business/permissions/audit/'
    | '/(private)/(dashboard)/business/subscription/checkout/'
    | '/(private)/(dashboard)/business/subscription/credits/'
    | '/(private)/(dashboard)/business/subscription/invoices/'
    | '/(private)/(dashboard)/business/subscription/plans/'
    | '/(private)/(dashboard)/business/subscription/pricing/'
    | '/(private)/(dashboard)/business/subscription/quotes/'
    | '/(private)/(dashboard)/business/subscription/reactivate/'
    | '/(private)/(dashboard)/business/subscription/success/'
    | '/(private)/(dashboard)/business/subscription/quotes/$quoteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  hybridRouteRoute: typeof hybridRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookStripeRoute: typeof ApiBillingWebhookStripeRoute
  ApiBillingWebhookIndexRoute: typeof ApiBillingWebhookIndexRoute
  ApiCronDailyIndexRoute: typeof ApiCronDailyIndexRoute
  ApiCronHourlyIndexRoute: typeof ApiCronHourlyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hybrid)': {
      id: '/(hybrid)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof hybridRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(hybrid)/unauthorized': {
      id: '/(hybrid)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof hybridUnauthorizedRouteImport
      parentRoute: typeof hybridRouteRoute
    }
    '/(private)/(dashboard)': {
      id: '/(private)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/register/': {
      id: '/(public)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof publicRegisterIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/tasks/': {
      id: '/(private)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof privateTasksIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/pos/': {
      id: '/(private)/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof privatePosIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/orders/': {
      id: '/(private)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof privateOrdersIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register/business-setup': {
      id: '/(public)/register/business-setup'
      path: '/register/business-setup'
      fullPath: '/register/business-setup'
      preLoaderRoute: typeof publicRegisterBusinessSetupRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/(dashboard)/notifications': {
      id: '/(private)/(dashboard)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof privatedashboardNotificationsRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/dashboard': {
      id: '/(private)/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privatedashboardDashboardRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/contact-us': {
      id: '/(private)/(dashboard)/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof privatedashboardContactUsRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/settings': {
      id: '/(private)/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privatedashboardSettingsRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/preparation': {
      id: '/(private)/(dashboard)/preparation'
      path: '/preparation'
      fullPath: '/preparation'
      preLoaderRoute: typeof privatedashboardPreparationRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/business': {
      id: '/(private)/(dashboard)/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof privatedashboardBusinessRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/billing': {
      id: '/(private)/(dashboard)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof privatedashboardBillingRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/account': {
      id: '/(private)/(dashboard)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof privatedashboardAccountRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/api/cron/hourly/': {
      id: '/api/cron/hourly/'
      path: '/api/cron/hourly'
      fullPath: '/api/cron/hourly/'
      preLoaderRoute: typeof ApiCronHourlyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily/': {
      id: '/api/cron/daily/'
      path: '/api/cron/daily'
      fullPath: '/api/cron/daily/'
      preLoaderRoute: typeof ApiCronDailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook/': {
      id: '/api/billing/webhook/'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook/'
      preLoaderRoute: typeof ApiBillingWebhookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/tasks/create/': {
      id: '/(private)/tasks/create/'
      path: '/tasks/create'
      fullPath: '/tasks/create/'
      preLoaderRoute: typeof privateTasksCreateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/tasks/$taskId/': {
      id: '/(private)/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof privateTasksTaskIdIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(dashboard)/transactions/': {
      id: '/(private)/(dashboard)/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof privatedashboardTransactionsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/settings/': {
      id: '/(private)/(dashboard)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof privatedashboardSettingsIndexRouteImport
      parentRoute: typeof privatedashboardSettingsRouteRoute
    }
    '/(private)/(dashboard)/sales-reports/': {
      id: '/(private)/(dashboard)/sales-reports/'
      path: '/sales-reports'
      fullPath: '/sales-reports/'
      preLoaderRoute: typeof privatedashboardSalesReportsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/purchases/': {
      id: '/(private)/(dashboard)/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof privatedashboardPurchasesIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/products/': {
      id: '/(private)/(dashboard)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof privatedashboardProductsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/preparation/': {
      id: '/(private)/(dashboard)/preparation/'
      path: '/'
      fullPath: '/preparation/'
      preLoaderRoute: typeof privatedashboardPreparationIndexRouteImport
      parentRoute: typeof privatedashboardPreparationRouteRoute
    }
    '/(private)/(dashboard)/order-history/': {
      id: '/(private)/(dashboard)/order-history/'
      path: '/order-history'
      fullPath: '/order-history/'
      preLoaderRoute: typeof privatedashboardOrderHistoryIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/inventory-reports/': {
      id: '/(private)/(dashboard)/inventory-reports/'
      path: '/inventory-reports'
      fullPath: '/inventory-reports/'
      preLoaderRoute: typeof privatedashboardInventoryReportsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/ingredients/': {
      id: '/(private)/(dashboard)/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof privatedashboardIngredientsIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/employees/': {
      id: '/(private)/(dashboard)/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof privatedashboardEmployeesIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/business/': {
      id: '/(private)/(dashboard)/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof privatedashboardBusinessIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/billing/': {
      id: '/(private)/(dashboard)/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof privatedashboardBillingIndexRouteImport
      parentRoute: typeof privatedashboardBillingRouteRoute
    }
    '/(private)/(dashboard)/account/': {
      id: '/(private)/(dashboard)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof privatedashboardAccountIndexRouteImport
      parentRoute: typeof privatedashboardAccountRouteRoute
    }
    '/api/billing/webhook/stripe': {
      id: '/api/billing/webhook/stripe'
      path: '/api/billing/webhook/stripe'
      fullPath: '/api/billing/webhook/stripe'
      preLoaderRoute: typeof ApiBillingWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)/settings/compliance': {
      id: '/(private)/(dashboard)/settings/compliance'
      path: '/compliance'
      fullPath: '/settings/compliance'
      preLoaderRoute: typeof privatedashboardSettingsComplianceRouteImport
      parentRoute: typeof privatedashboardSettingsRouteRoute
    }
    '/(private)/(dashboard)/preparation/history': {
      id: '/(private)/(dashboard)/preparation/history'
      path: '/history'
      fullPath: '/preparation/history'
      preLoaderRoute: typeof privatedashboardPreparationHistoryRouteImport
      parentRoute: typeof privatedashboardPreparationRouteRoute
    }
    '/(private)/(dashboard)/billing/manual-payment': {
      id: '/(private)/(dashboard)/billing/manual-payment'
      path: '/manual-payment'
      fullPath: '/billing/manual-payment'
      preLoaderRoute: typeof privatedashboardBillingManualPaymentRouteImport
      parentRoute: typeof privatedashboardBillingRouteRoute
    }
    '/(private)/(dashboard)/business/suppliers': {
      id: '/(private)/(dashboard)/business/suppliers'
      path: '/suppliers'
      fullPath: '/business/suppliers'
      preLoaderRoute: typeof privatedashboardBusinessSuppliersRouteRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/subscription': {
      id: '/(private)/(dashboard)/business/subscription'
      path: '/subscription'
      fullPath: '/business/subscription'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionRouteRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/customers': {
      id: '/(private)/(dashboard)/business/customers'
      path: '/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof privatedashboardBusinessCustomersRouteRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/transactions/$transactionId/': {
      id: '/(private)/(dashboard)/transactions/$transactionId/'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId/'
      preLoaderRoute: typeof privatedashboardTransactionsTransactionIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/purchases/$purchaseId/': {
      id: '/(private)/(dashboard)/purchases/$purchaseId/'
      path: '/purchases/$purchaseId'
      fullPath: '/purchases/$purchaseId/'
      preLoaderRoute: typeof privatedashboardPurchasesPurchaseIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/products/create/': {
      id: '/(private)/(dashboard)/products/create/'
      path: '/products/create'
      fullPath: '/products/create/'
      preLoaderRoute: typeof privatedashboardProductsCreateIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/products/$productId/': {
      id: '/(private)/(dashboard)/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof privatedashboardProductsProductIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/order-history/$orderId/': {
      id: '/(private)/(dashboard)/order-history/$orderId/'
      path: '/order-history/$orderId'
      fullPath: '/order-history/$orderId/'
      preLoaderRoute: typeof privatedashboardOrderHistoryOrderIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/ingredients/create/': {
      id: '/(private)/(dashboard)/ingredients/create/'
      path: '/ingredients/create'
      fullPath: '/ingredients/create/'
      preLoaderRoute: typeof privatedashboardIngredientsCreateIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/ingredients/$ingredientId/': {
      id: '/(private)/(dashboard)/ingredients/$ingredientId/'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId/'
      preLoaderRoute: typeof privatedashboardIngredientsIngredientIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/employees/create/': {
      id: '/(private)/(dashboard)/employees/create/'
      path: '/employees/create'
      fullPath: '/employees/create/'
      preLoaderRoute: typeof privatedashboardEmployeesCreateIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/employees/$employeeId/': {
      id: '/(private)/(dashboard)/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof privatedashboardEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/business/suppliers/': {
      id: '/(private)/(dashboard)/business/suppliers/'
      path: '/'
      fullPath: '/business/suppliers/'
      preLoaderRoute: typeof privatedashboardBusinessSuppliersIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSuppliersRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/': {
      id: '/(private)/(dashboard)/business/subscription/'
      path: '/'
      fullPath: '/business/subscription/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/profile/': {
      id: '/(private)/(dashboard)/business/profile/'
      path: '/profile'
      fullPath: '/business/profile/'
      preLoaderRoute: typeof privatedashboardBusinessProfileIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/permissions/': {
      id: '/(private)/(dashboard)/business/permissions/'
      path: '/permissions'
      fullPath: '/business/permissions/'
      preLoaderRoute: typeof privatedashboardBusinessPermissionsIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/customers/': {
      id: '/(private)/(dashboard)/business/customers/'
      path: '/'
      fullPath: '/business/customers/'
      preLoaderRoute: typeof privatedashboardBusinessCustomersIndexRouteImport
      parentRoute: typeof privatedashboardBusinessCustomersRouteRoute
    }
    '/(private)/(dashboard)/business/capabilities/': {
      id: '/(private)/(dashboard)/business/capabilities/'
      path: '/capabilities'
      fullPath: '/business/capabilities/'
      preLoaderRoute: typeof privatedashboardBusinessCapabilitiesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/branches/': {
      id: '/(private)/(dashboard)/business/branches/'
      path: '/branches'
      fullPath: '/business/branches/'
      preLoaderRoute: typeof privatedashboardBusinessBranchesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/account/security/': {
      id: '/(private)/(dashboard)/account/security/'
      path: '/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof privatedashboardAccountSecurityIndexRouteImport
      parentRoute: typeof privatedashboardAccountRouteRoute
    }
    '/(private)/(dashboard)/account/preferences/': {
      id: '/(private)/(dashboard)/account/preferences/'
      path: '/preferences'
      fullPath: '/account/preferences/'
      preLoaderRoute: typeof privatedashboardAccountPreferencesIndexRouteImport
      parentRoute: typeof privatedashboardAccountRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/payment-methods': {
      id: '/(private)/(dashboard)/business/subscription/payment-methods'
      path: '/payment-methods'
      fullPath: '/business/subscription/payment-methods'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionPaymentMethodsRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/success/': {
      id: '/(private)/(dashboard)/business/subscription/success/'
      path: '/success'
      fullPath: '/business/subscription/success/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionSuccessIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/reactivate/': {
      id: '/(private)/(dashboard)/business/subscription/reactivate/'
      path: '/reactivate'
      fullPath: '/business/subscription/reactivate/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionReactivateIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/quotes/': {
      id: '/(private)/(dashboard)/business/subscription/quotes/'
      path: '/quotes'
      fullPath: '/business/subscription/quotes/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionQuotesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/pricing/': {
      id: '/(private)/(dashboard)/business/subscription/pricing/'
      path: '/pricing'
      fullPath: '/business/subscription/pricing/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionPricingIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/plans/': {
      id: '/(private)/(dashboard)/business/subscription/plans/'
      path: '/plans'
      fullPath: '/business/subscription/plans/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionPlansIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/invoices/': {
      id: '/(private)/(dashboard)/business/subscription/invoices/'
      path: '/invoices'
      fullPath: '/business/subscription/invoices/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionInvoicesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/credits/': {
      id: '/(private)/(dashboard)/business/subscription/credits/'
      path: '/credits'
      fullPath: '/business/subscription/credits/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionCreditsIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/checkout/': {
      id: '/(private)/(dashboard)/business/subscription/checkout/'
      path: '/checkout'
      fullPath: '/business/subscription/checkout/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionCheckoutIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/permissions/audit/': {
      id: '/(private)/(dashboard)/business/permissions/audit/'
      path: '/permissions/audit'
      fullPath: '/business/permissions/audit/'
      preLoaderRoute: typeof privatedashboardBusinessPermissionsAuditIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/billing/credits/checkout/': {
      id: '/(private)/(dashboard)/billing/credits/checkout/'
      path: '/credits/checkout'
      fullPath: '/billing/credits/checkout/'
      preLoaderRoute: typeof privatedashboardBillingCreditsCheckoutIndexRouteImport
      parentRoute: typeof privatedashboardBillingRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/quotes/$quoteId/': {
      id: '/(private)/(dashboard)/business/subscription/quotes/$quoteId/'
      path: '/quotes/$quoteId'
      fullPath: '/business/subscription/quotes/$quoteId/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
  }
}

interface hybridRouteRouteChildren {
  hybridUnauthorizedRoute: typeof hybridUnauthorizedRoute
}

const hybridRouteRouteChildren: hybridRouteRouteChildren = {
  hybridUnauthorizedRoute: hybridUnauthorizedRoute,
}

const hybridRouteRouteWithChildren = hybridRouteRoute._addFileChildren(
  hybridRouteRouteChildren,
)

interface privatedashboardAccountRouteRouteChildren {
  privatedashboardAccountIndexRoute: typeof privatedashboardAccountIndexRoute
  privatedashboardAccountPreferencesIndexRoute: typeof privatedashboardAccountPreferencesIndexRoute
  privatedashboardAccountSecurityIndexRoute: typeof privatedashboardAccountSecurityIndexRoute
}

const privatedashboardAccountRouteRouteChildren: privatedashboardAccountRouteRouteChildren =
  {
    privatedashboardAccountIndexRoute: privatedashboardAccountIndexRoute,
    privatedashboardAccountPreferencesIndexRoute:
      privatedashboardAccountPreferencesIndexRoute,
    privatedashboardAccountSecurityIndexRoute:
      privatedashboardAccountSecurityIndexRoute,
  }

const privatedashboardAccountRouteRouteWithChildren =
  privatedashboardAccountRouteRoute._addFileChildren(
    privatedashboardAccountRouteRouteChildren,
  )

interface privatedashboardBillingRouteRouteChildren {
  privatedashboardBillingManualPaymentRoute: typeof privatedashboardBillingManualPaymentRoute
  privatedashboardBillingIndexRoute: typeof privatedashboardBillingIndexRoute
  privatedashboardBillingCreditsCheckoutIndexRoute: typeof privatedashboardBillingCreditsCheckoutIndexRoute
}

const privatedashboardBillingRouteRouteChildren: privatedashboardBillingRouteRouteChildren =
  {
    privatedashboardBillingManualPaymentRoute:
      privatedashboardBillingManualPaymentRoute,
    privatedashboardBillingIndexRoute: privatedashboardBillingIndexRoute,
    privatedashboardBillingCreditsCheckoutIndexRoute:
      privatedashboardBillingCreditsCheckoutIndexRoute,
  }

const privatedashboardBillingRouteRouteWithChildren =
  privatedashboardBillingRouteRoute._addFileChildren(
    privatedashboardBillingRouteRouteChildren,
  )

interface privatedashboardBusinessCustomersRouteRouteChildren {
  privatedashboardBusinessCustomersIndexRoute: typeof privatedashboardBusinessCustomersIndexRoute
}

const privatedashboardBusinessCustomersRouteRouteChildren: privatedashboardBusinessCustomersRouteRouteChildren =
  {
    privatedashboardBusinessCustomersIndexRoute:
      privatedashboardBusinessCustomersIndexRoute,
  }

const privatedashboardBusinessCustomersRouteRouteWithChildren =
  privatedashboardBusinessCustomersRouteRoute._addFileChildren(
    privatedashboardBusinessCustomersRouteRouteChildren,
  )

interface privatedashboardBusinessSubscriptionRouteRouteChildren {
  privatedashboardBusinessSubscriptionPaymentMethodsRoute: typeof privatedashboardBusinessSubscriptionPaymentMethodsRoute
  privatedashboardBusinessSubscriptionIndexRoute: typeof privatedashboardBusinessSubscriptionIndexRoute
  privatedashboardBusinessSubscriptionCheckoutIndexRoute: typeof privatedashboardBusinessSubscriptionCheckoutIndexRoute
  privatedashboardBusinessSubscriptionCreditsIndexRoute: typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  privatedashboardBusinessSubscriptionInvoicesIndexRoute: typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  privatedashboardBusinessSubscriptionPlansIndexRoute: typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  privatedashboardBusinessSubscriptionPricingIndexRoute: typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  privatedashboardBusinessSubscriptionQuotesIndexRoute: typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  privatedashboardBusinessSubscriptionReactivateIndexRoute: typeof privatedashboardBusinessSubscriptionReactivateIndexRoute
  privatedashboardBusinessSubscriptionSuccessIndexRoute: typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute: typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}

const privatedashboardBusinessSubscriptionRouteRouteChildren: privatedashboardBusinessSubscriptionRouteRouteChildren =
  {
    privatedashboardBusinessSubscriptionPaymentMethodsRoute:
      privatedashboardBusinessSubscriptionPaymentMethodsRoute,
    privatedashboardBusinessSubscriptionIndexRoute:
      privatedashboardBusinessSubscriptionIndexRoute,
    privatedashboardBusinessSubscriptionCheckoutIndexRoute:
      privatedashboardBusinessSubscriptionCheckoutIndexRoute,
    privatedashboardBusinessSubscriptionCreditsIndexRoute:
      privatedashboardBusinessSubscriptionCreditsIndexRoute,
    privatedashboardBusinessSubscriptionInvoicesIndexRoute:
      privatedashboardBusinessSubscriptionInvoicesIndexRoute,
    privatedashboardBusinessSubscriptionPlansIndexRoute:
      privatedashboardBusinessSubscriptionPlansIndexRoute,
    privatedashboardBusinessSubscriptionPricingIndexRoute:
      privatedashboardBusinessSubscriptionPricingIndexRoute,
    privatedashboardBusinessSubscriptionQuotesIndexRoute:
      privatedashboardBusinessSubscriptionQuotesIndexRoute,
    privatedashboardBusinessSubscriptionReactivateIndexRoute:
      privatedashboardBusinessSubscriptionReactivateIndexRoute,
    privatedashboardBusinessSubscriptionSuccessIndexRoute:
      privatedashboardBusinessSubscriptionSuccessIndexRoute,
    privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute:
      privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute,
  }

const privatedashboardBusinessSubscriptionRouteRouteWithChildren =
  privatedashboardBusinessSubscriptionRouteRoute._addFileChildren(
    privatedashboardBusinessSubscriptionRouteRouteChildren,
  )

interface privatedashboardBusinessSuppliersRouteRouteChildren {
  privatedashboardBusinessSuppliersIndexRoute: typeof privatedashboardBusinessSuppliersIndexRoute
}

const privatedashboardBusinessSuppliersRouteRouteChildren: privatedashboardBusinessSuppliersRouteRouteChildren =
  {
    privatedashboardBusinessSuppliersIndexRoute:
      privatedashboardBusinessSuppliersIndexRoute,
  }

const privatedashboardBusinessSuppliersRouteRouteWithChildren =
  privatedashboardBusinessSuppliersRouteRoute._addFileChildren(
    privatedashboardBusinessSuppliersRouteRouteChildren,
  )

interface privatedashboardBusinessRouteRouteChildren {
  privatedashboardBusinessCustomersRouteRoute: typeof privatedashboardBusinessCustomersRouteRouteWithChildren
  privatedashboardBusinessSubscriptionRouteRoute: typeof privatedashboardBusinessSubscriptionRouteRouteWithChildren
  privatedashboardBusinessSuppliersRouteRoute: typeof privatedashboardBusinessSuppliersRouteRouteWithChildren
  privatedashboardBusinessIndexRoute: typeof privatedashboardBusinessIndexRoute
  privatedashboardBusinessBranchesIndexRoute: typeof privatedashboardBusinessBranchesIndexRoute
  privatedashboardBusinessCapabilitiesIndexRoute: typeof privatedashboardBusinessCapabilitiesIndexRoute
  privatedashboardBusinessPermissionsIndexRoute: typeof privatedashboardBusinessPermissionsIndexRoute
  privatedashboardBusinessProfileIndexRoute: typeof privatedashboardBusinessProfileIndexRoute
  privatedashboardBusinessPermissionsAuditIndexRoute: typeof privatedashboardBusinessPermissionsAuditIndexRoute
}

const privatedashboardBusinessRouteRouteChildren: privatedashboardBusinessRouteRouteChildren =
  {
    privatedashboardBusinessCustomersRouteRoute:
      privatedashboardBusinessCustomersRouteRouteWithChildren,
    privatedashboardBusinessSubscriptionRouteRoute:
      privatedashboardBusinessSubscriptionRouteRouteWithChildren,
    privatedashboardBusinessSuppliersRouteRoute:
      privatedashboardBusinessSuppliersRouteRouteWithChildren,
    privatedashboardBusinessIndexRoute: privatedashboardBusinessIndexRoute,
    privatedashboardBusinessBranchesIndexRoute:
      privatedashboardBusinessBranchesIndexRoute,
    privatedashboardBusinessCapabilitiesIndexRoute:
      privatedashboardBusinessCapabilitiesIndexRoute,
    privatedashboardBusinessPermissionsIndexRoute:
      privatedashboardBusinessPermissionsIndexRoute,
    privatedashboardBusinessProfileIndexRoute:
      privatedashboardBusinessProfileIndexRoute,
    privatedashboardBusinessPermissionsAuditIndexRoute:
      privatedashboardBusinessPermissionsAuditIndexRoute,
  }

const privatedashboardBusinessRouteRouteWithChildren =
  privatedashboardBusinessRouteRoute._addFileChildren(
    privatedashboardBusinessRouteRouteChildren,
  )

interface privatedashboardPreparationRouteRouteChildren {
  privatedashboardPreparationHistoryRoute: typeof privatedashboardPreparationHistoryRoute
  privatedashboardPreparationIndexRoute: typeof privatedashboardPreparationIndexRoute
}

const privatedashboardPreparationRouteRouteChildren: privatedashboardPreparationRouteRouteChildren =
  {
    privatedashboardPreparationHistoryRoute:
      privatedashboardPreparationHistoryRoute,
    privatedashboardPreparationIndexRoute:
      privatedashboardPreparationIndexRoute,
  }

const privatedashboardPreparationRouteRouteWithChildren =
  privatedashboardPreparationRouteRoute._addFileChildren(
    privatedashboardPreparationRouteRouteChildren,
  )

interface privatedashboardSettingsRouteRouteChildren {
  privatedashboardSettingsComplianceRoute: typeof privatedashboardSettingsComplianceRoute
  privatedashboardSettingsIndexRoute: typeof privatedashboardSettingsIndexRoute
}

const privatedashboardSettingsRouteRouteChildren: privatedashboardSettingsRouteRouteChildren =
  {
    privatedashboardSettingsComplianceRoute:
      privatedashboardSettingsComplianceRoute,
    privatedashboardSettingsIndexRoute: privatedashboardSettingsIndexRoute,
  }

const privatedashboardSettingsRouteRouteWithChildren =
  privatedashboardSettingsRouteRoute._addFileChildren(
    privatedashboardSettingsRouteRouteChildren,
  )

interface privatedashboardRouteRouteChildren {
  privatedashboardAccountRouteRoute: typeof privatedashboardAccountRouteRouteWithChildren
  privatedashboardBillingRouteRoute: typeof privatedashboardBillingRouteRouteWithChildren
  privatedashboardBusinessRouteRoute: typeof privatedashboardBusinessRouteRouteWithChildren
  privatedashboardPreparationRouteRoute: typeof privatedashboardPreparationRouteRouteWithChildren
  privatedashboardSettingsRouteRoute: typeof privatedashboardSettingsRouteRouteWithChildren
  privatedashboardContactUsRoute: typeof privatedashboardContactUsRoute
  privatedashboardDashboardRoute: typeof privatedashboardDashboardRoute
  privatedashboardNotificationsRoute: typeof privatedashboardNotificationsRoute
  privatedashboardEmployeesIndexRoute: typeof privatedashboardEmployeesIndexRoute
  privatedashboardIngredientsIndexRoute: typeof privatedashboardIngredientsIndexRoute
  privatedashboardInventoryReportsIndexRoute: typeof privatedashboardInventoryReportsIndexRoute
  privatedashboardOrderHistoryIndexRoute: typeof privatedashboardOrderHistoryIndexRoute
  privatedashboardProductsIndexRoute: typeof privatedashboardProductsIndexRoute
  privatedashboardPurchasesIndexRoute: typeof privatedashboardPurchasesIndexRoute
  privatedashboardSalesReportsIndexRoute: typeof privatedashboardSalesReportsIndexRoute
  privatedashboardTransactionsIndexRoute: typeof privatedashboardTransactionsIndexRoute
  privatedashboardEmployeesEmployeeIdIndexRoute: typeof privatedashboardEmployeesEmployeeIdIndexRoute
  privatedashboardEmployeesCreateIndexRoute: typeof privatedashboardEmployeesCreateIndexRoute
  privatedashboardIngredientsIngredientIdIndexRoute: typeof privatedashboardIngredientsIngredientIdIndexRoute
  privatedashboardIngredientsCreateIndexRoute: typeof privatedashboardIngredientsCreateIndexRoute
  privatedashboardOrderHistoryOrderIdIndexRoute: typeof privatedashboardOrderHistoryOrderIdIndexRoute
  privatedashboardProductsProductIdIndexRoute: typeof privatedashboardProductsProductIdIndexRoute
  privatedashboardProductsCreateIndexRoute: typeof privatedashboardProductsCreateIndexRoute
  privatedashboardPurchasesPurchaseIdIndexRoute: typeof privatedashboardPurchasesPurchaseIdIndexRoute
  privatedashboardTransactionsTransactionIdIndexRoute: typeof privatedashboardTransactionsTransactionIdIndexRoute
}

const privatedashboardRouteRouteChildren: privatedashboardRouteRouteChildren = {
  privatedashboardAccountRouteRoute:
    privatedashboardAccountRouteRouteWithChildren,
  privatedashboardBillingRouteRoute:
    privatedashboardBillingRouteRouteWithChildren,
  privatedashboardBusinessRouteRoute:
    privatedashboardBusinessRouteRouteWithChildren,
  privatedashboardPreparationRouteRoute:
    privatedashboardPreparationRouteRouteWithChildren,
  privatedashboardSettingsRouteRoute:
    privatedashboardSettingsRouteRouteWithChildren,
  privatedashboardContactUsRoute: privatedashboardContactUsRoute,
  privatedashboardDashboardRoute: privatedashboardDashboardRoute,
  privatedashboardNotificationsRoute: privatedashboardNotificationsRoute,
  privatedashboardEmployeesIndexRoute: privatedashboardEmployeesIndexRoute,
  privatedashboardIngredientsIndexRoute: privatedashboardIngredientsIndexRoute,
  privatedashboardInventoryReportsIndexRoute:
    privatedashboardInventoryReportsIndexRoute,
  privatedashboardOrderHistoryIndexRoute:
    privatedashboardOrderHistoryIndexRoute,
  privatedashboardProductsIndexRoute: privatedashboardProductsIndexRoute,
  privatedashboardPurchasesIndexRoute: privatedashboardPurchasesIndexRoute,
  privatedashboardSalesReportsIndexRoute:
    privatedashboardSalesReportsIndexRoute,
  privatedashboardTransactionsIndexRoute:
    privatedashboardTransactionsIndexRoute,
  privatedashboardEmployeesEmployeeIdIndexRoute:
    privatedashboardEmployeesEmployeeIdIndexRoute,
  privatedashboardEmployeesCreateIndexRoute:
    privatedashboardEmployeesCreateIndexRoute,
  privatedashboardIngredientsIngredientIdIndexRoute:
    privatedashboardIngredientsIngredientIdIndexRoute,
  privatedashboardIngredientsCreateIndexRoute:
    privatedashboardIngredientsCreateIndexRoute,
  privatedashboardOrderHistoryOrderIdIndexRoute:
    privatedashboardOrderHistoryOrderIdIndexRoute,
  privatedashboardProductsProductIdIndexRoute:
    privatedashboardProductsProductIdIndexRoute,
  privatedashboardProductsCreateIndexRoute:
    privatedashboardProductsCreateIndexRoute,
  privatedashboardPurchasesPurchaseIdIndexRoute:
    privatedashboardPurchasesPurchaseIdIndexRoute,
  privatedashboardTransactionsTransactionIdIndexRoute:
    privatedashboardTransactionsTransactionIdIndexRoute,
}

const privatedashboardRouteRouteWithChildren =
  privatedashboardRouteRoute._addFileChildren(
    privatedashboardRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privatedashboardRouteRoute: typeof privatedashboardRouteRouteWithChildren
  privateOrdersIndexRoute: typeof privateOrdersIndexRoute
  privatePosIndexRoute: typeof privatePosIndexRoute
  privateTasksIndexRoute: typeof privateTasksIndexRoute
  privateTasksTaskIdIndexRoute: typeof privateTasksTaskIdIndexRoute
  privateTasksCreateIndexRoute: typeof privateTasksCreateIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatedashboardRouteRoute: privatedashboardRouteRouteWithChildren,
  privateOrdersIndexRoute: privateOrdersIndexRoute,
  privatePosIndexRoute: privatePosIndexRoute,
  privateTasksIndexRoute: privateTasksIndexRoute,
  privateTasksTaskIdIndexRoute: privateTasksTaskIdIndexRoute,
  privateTasksCreateIndexRoute: privateTasksCreateIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
  publicRegisterBusinessSetupRoute: typeof publicRegisterBusinessSetupRoute
  publicRegisterIndexRoute: typeof publicRegisterIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
  publicRegisterBusinessSetupRoute: publicRegisterBusinessSetupRoute,
  publicRegisterIndexRoute: publicRegisterIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  hybridRouteRoute: hybridRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookStripeRoute: ApiBillingWebhookStripeRoute,
  ApiBillingWebhookIndexRoute: ApiBillingWebhookIndexRoute,
  ApiCronDailyIndexRoute: ApiCronDailyIndexRoute,
  ApiCronHourlyIndexRoute: ApiCronHourlyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
