/**
 * seed-configuration-definitions.ts
 *
 * Seeds ConfigurationDefinition table with all configuration metadata.
 * This is the "base layer" of the three-pillar Configuration System.
 */

import type { PrismaClient } from 'prisma/generated/prisma/client'

export async function seedConfigurationDefinitions(prisma: PrismaClient) {
  console.log('🔧 Seeding configuration definitions...')

  const definitions = [
    // ═══════════════════════════════════════════════════════════
    // TAX & COMPLIANCE CONFIGURATION
    // ═══════════════════════════════════════════════════════════
    {
      id: 'VAT_RATE',
      key: 'VAT_RATE',
      label: 'VAT Rate',
      description: 'Value-added tax rate (as decimal, e.g., 0.12 for 12%)',
      category: 'TAX',
      dataType: 'NUMBER',
      defaultValue: '0.12',
      scope: 'BUSINESS',
      required: true,
      validation: { min: 0, max: 1 },
      countryCode: null,
    },
    {
      id: 'IS_VAT_REGISTERED',
      key: 'IS_VAT_REGISTERED',
      label: 'VAT Registered',
      description: 'Whether the business is registered for VAT/GST',
      category: 'TAX',
      dataType: 'BOOLEAN',
      defaultValue: 'false',
      scope: 'BUSINESS',
      required: true,
      validation: { enum: ['true', 'false'] },
      countryCode: null,
    },
    {
      id: 'PRICE_CONFIGURATION',
      key: 'PRICE_CONFIGURATION',
      label: 'Price Display Mode',
      description: 'Whether prices are displayed inclusive or exclusive of tax',
      category: 'TAX',
      dataType: 'ENUM',
      defaultValue: 'EXCLUSIVE',
      scope: 'BUSINESS',
      required: true,
      validation: { enum: ['INCLUSIVE', 'EXCLUSIVE'] },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // LOCALE & REGIONAL SETTINGS
    // ═══════════════════════════════════════════════════════════
    {
      id: 'LOCALE',
      key: 'LOCALE',
      label: 'Locale',
      description: 'Regional locale setting (e.g., en-PH, en-SG, en-US)',
      category: 'LOCALE',
      dataType: 'STRING',
      defaultValue: 'en-PH',
      scope: 'BUSINESS',
      required: true,
      validation: { regex: '^[a-z]{2}-[A-Z]{2}$' },
      countryCode: null,
    },
    {
      id: 'CURRENCY',
      key: 'CURRENCY',
      label: 'Currency',
      description: 'Currency code (e.g., PHP, SGD, USD)',
      category: 'LOCALE',
      dataType: 'STRING',
      defaultValue: 'PHP',
      scope: 'BUSINESS',
      required: true,
      validation: { regex: '^[A-Z]{3}$' },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // OPERATIONAL SETTINGS
    // ═══════════════════════════════════════════════════════════
    {
      id: 'LOW_STOCK_THRESHOLD',
      key: 'LOW_STOCK_THRESHOLD',
      label: 'Low Stock Threshold',
      description: 'Quantity threshold for low stock alerts',
      category: 'OPERATIONAL',
      dataType: 'NUMBER',
      defaultValue: '10',
      scope: 'BUSINESS',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'BUFFER_RATE',
      key: 'BUFFER_RATE',
      label: 'Buffer Rate',
      description: 'Safety buffer percentage for inventory calculations',
      category: 'OPERATIONAL',
      dataType: 'NUMBER',
      defaultValue: '0.05',
      scope: 'BUSINESS',
      required: false,
      validation: { min: 0, max: 1 },
      countryCode: null,
    },
    {
      id: 'AUTO_APPROVE_LOW_STOCK_REFILL',
      key: 'AUTO_APPROVE_LOW_STOCK_REFILL',
      label: 'Auto-approve Low Stock Refills',
      description: 'Automatically approve SHELF_REFILL tasks on low-stock detection',
      category: 'OPERATIONAL',
      dataType: 'BOOLEAN',
      defaultValue: 'true',
      scope: 'BUSINESS',
      required: false,
      validation: { enum: ['true', 'false'] },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // REFUND POLICY
    // ═══════════════════════════════════════════════════════════
    {
      id: 'REFUND_WINDOW_HOURS',
      key: 'REFUND_WINDOW_HOURS',
      label: 'Refund Window (Hours)',
      description: 'How many hours after a sale a refund can be issued. -1 = unlimited, 0 = refunds disabled, any positive value = hours allowed.',
      category: 'OPERATIONAL',
      dataType: 'NUMBER',
      defaultValue: '-1',
      scope: 'BUSINESS',
      required: false,
      validation: { min: -1 },
      countryCode: null,
    },
    {
      id: 'REFUND_REQUIRES_SUPERVISOR',
      key: 'REFUND_REQUIRES_SUPERVISOR',
      label: 'Require Supervisor for Refunds',
      description: 'When enabled, only users with Supervisor or Admin role can issue refunds.',
      category: 'OPERATIONAL',
      dataType: 'BOOLEAN',
      defaultValue: 'false',
      scope: 'BUSINESS',
      required: false,
      validation: { enum: ['true', 'false'] },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // BILLING & SUBSCRIPTION POLICIES (Platform-scoped)
    // ═══════════════════════════════════════════════════════════
    {
      id: 'TRIAL_DURATION_DAYS',
      key: 'TRIAL_DURATION_DAYS',
      label: 'Trial Duration (Days)',
      description: 'Number of days for trial period',
      category: 'BILLING',
      dataType: 'NUMBER',
      defaultValue: '30',
      scope: 'PLATFORM',
      required: true,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'GRACE_PERIOD_DAYS',
      key: 'GRACE_PERIOD_DAYS',
      label: 'Grace Period (Days)',
      description: 'Days after expiry before hard restriction',
      category: 'BILLING',
      dataType: 'NUMBER',
      defaultValue: '7',
      scope: 'PLATFORM',
      required: true,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'LONG_TERM_INACTIVE_DAYS',
      key: 'LONG_TERM_INACTIVE_DAYS',
      label: 'Long-term Inactive Threshold (Days)',
      description: 'Days after expiry before marked as long-term inactive',
      category: 'BILLING',
      dataType: 'NUMBER',
      defaultValue: '90',
      scope: 'PLATFORM',
      required: true,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'CREDIT_LOW_BALANCE_THRESHOLD',
      key: 'CREDIT_LOW_BALANCE_THRESHOLD',
      label: 'Credit Low Balance Threshold',
      description: 'Notify when credits fall below this amount',
      category: 'BILLING',
      dataType: 'NUMBER',
      defaultValue: '10',
      scope: 'PLATFORM',
      required: true,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'OVERAGE_BILLING_ENABLED',
      key: 'OVERAGE_BILLING_ENABLED',
      label: 'Overage Billing Enabled',
      description: 'Whether to charge for overages vs. blocking transactions',
      category: 'BILLING',
      dataType: 'BOOLEAN',
      defaultValue: 'false',
      scope: 'PLATFORM',
      required: true,
      validation: { enum: ['true', 'false'] },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // COMPOSABLE PRICING (Platform-scoped)
    // ═══════════════════════════════════════════════════════════
    {
      id: 'COMPOSABLE_BRANCH_MONTHLY_RATE',
      key: 'COMPOSABLE_BRANCH_MONTHLY_RATE',
      label: 'Composable Branch Monthly Rate',
      description: 'Extra monthly charge per branch in composable subscriptions (cents)',
      category: 'COMPOSABLE_PRICING',
      dataType: 'NUMBER',
      defaultValue: '0',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'COMPOSABLE_MAX_FEATURES',
      key: 'COMPOSABLE_MAX_FEATURES',
      label: 'Composable Max Features',
      description: 'Maximum feature selections (0 = unlimited)',
      category: 'COMPOSABLE_PRICING',
      dataType: 'NUMBER',
      defaultValue: '0',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'COMPOSABLE_ANNUAL_DISCOUNT_PCT',
      key: 'COMPOSABLE_ANNUAL_DISCOUNT_PCT',
      label: 'Composable Annual Discount %',
      description: 'Annual billing discount in basis points (e.g., 1000 = 10%)',
      category: 'COMPOSABLE_PRICING',
      dataType: 'NUMBER',
      defaultValue: '0',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0, max: 10000 },
      countryCode: null,
    },
    {
      id: 'COMPOSABLE_TAX_RATE',
      key: 'COMPOSABLE_TAX_RATE',
      label: 'Composable Tax Rate',
      description: 'Tax rate for composable subscriptions (basis points)',
      category: 'COMPOSABLE_PRICING',
      dataType: 'NUMBER',
      defaultValue: '0',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0, max: 10000 },
      countryCode: null,
    },
    {
      id: 'COMPOSABLE_QUOTE_VALIDITY_DAYS',
      key: 'COMPOSABLE_QUOTE_VALIDITY_DAYS',
      label: 'Quote Validity (Days)',
      description: 'Days before un-accepted quote expires',
      category: 'COMPOSABLE_PRICING',
      dataType: 'NUMBER',
      defaultValue: '30',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 1 },
      countryCode: null,
    },
    {
      id: 'COMPOSABLE_PARTNER_MARGIN_PCT',
      key: 'COMPOSABLE_PARTNER_MARGIN_PCT',
      label: 'Partner Margin %',
      description: 'Partner/reseller margin (basis points)',
      category: 'COMPOSABLE_PRICING',
      dataType: 'NUMBER',
      defaultValue: '0',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0, max: 10000 },
      countryCode: null,
    },
    {
      id: 'COMPOSABLE_PROMO_CODE_ENABLED',
      key: 'COMPOSABLE_PROMO_CODE_ENABLED',
      label: 'Promo Code Enabled',
      description: 'Whether promo code discount is active',
      category: 'COMPOSABLE_PRICING',
      dataType: 'BOOLEAN',
      defaultValue: 'false',
      scope: 'PLATFORM',
      required: false,
      validation: { enum: ['true', 'false'] },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // GUIDANCE SYSTEM (Platform-scoped)
    // ═══════════════════════════════════════════════════════════
    {
      id: 'HINT_FREQUENCY_DAYS',
      key: 'HINT_FREQUENCY_DAYS',
      label: 'Hint Frequency (Days)',
      description: 'Days between showing the same hint',
      category: 'GUIDANCE',
      dataType: 'NUMBER',
      defaultValue: '1',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'HINT_DISPLAY_SECONDS',
      key: 'HINT_DISPLAY_SECONDS',
      label: 'Hint Display Duration (Seconds)',
      description: 'Seconds before hint auto-dismisses',
      category: 'GUIDANCE',
      dataType: 'NUMBER',
      defaultValue: '6',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 1 },
      countryCode: null,
    },

    // ═══════════════════════════════════════════════════════════
    // ADD-ON PRICING (Platform-scoped)
    // ═══════════════════════════════════════════════════════════
    {
      id: 'ADDON_ANALYTICS_PRICE',
      key: 'ADDON_ANALYTICS_PRICE',
      label: 'Analytics Add-on Price',
      description: 'Monthly price for Analytics Dashboard (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '29900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_ANALYTICS_PRICE_ID',
      key: 'ADDON_ANALYTICS_PRICE_ID',
      label: 'Analytics Add-on Stripe Price ID',
      description: 'Stripe Price ID for Analytics Dashboard',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_API_PRICE',
      key: 'ADDON_API_PRICE',
      label: 'API Access Price',
      description: 'Monthly price for API Access (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '49900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_API_PRICE_ID',
      key: 'ADDON_API_PRICE_ID',
      label: 'API Access Stripe Price ID',
      description: 'Stripe Price ID for API Access',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_BRANCH_PRICE',
      key: 'ADDON_BRANCH_PRICE',
      label: 'Extra Branch Price',
      description: 'Monthly price per extra branch (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '19900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_BRANCH_PRICE_ID',
      key: 'ADDON_BRANCH_PRICE_ID',
      label: 'Extra Branch Stripe Price ID',
      description: 'Stripe Price ID for Extra Branch',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_EMPLOYEE_PRICE',
      key: 'ADDON_EMPLOYEE_PRICE',
      label: 'Extra Employee Price',
      description: 'Monthly price per extra employee (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '4900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_EMPLOYEE_PRICE_ID',
      key: 'ADDON_EMPLOYEE_PRICE_ID',
      label: 'Extra Employee Stripe Price ID',
      description: 'Stripe Price ID for Extra Employee',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },

    // Transaction Top-ups
    {
      id: 'ADDON_TX_500_PRICE',
      key: 'ADDON_TX_500_PRICE',
      label: '+500 TX Top-up Price',
      description: 'Price for +500 transaction top-up (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '9900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_TX_500_PRICE_ID',
      key: 'ADDON_TX_500_PRICE_ID',
      label: '+500 TX Stripe Price ID',
      description: 'Stripe Price ID for +500 TX top-up',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_TX_1000_PRICE',
      key: 'ADDON_TX_1000_PRICE',
      label: '+1000 TX Top-up Price',
      description: 'Price for +1,000 transaction top-up (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '17900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_TX_1000_PRICE_ID',
      key: 'ADDON_TX_1000_PRICE_ID',
      label: '+1000 TX Stripe Price ID',
      description: 'Stripe Price ID for +1,000 TX top-up',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_TX_5000_PRICE',
      key: 'ADDON_TX_5000_PRICE',
      label: '+5000 TX Top-up Price',
      description: 'Price for +5,000 transaction top-up (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '79900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_TX_5000_PRICE_ID',
      key: 'ADDON_TX_5000_PRICE_ID',
      label: '+5000 TX Stripe Price ID',
      description: 'Stripe Price ID for +5,000 TX top-up',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },

    // Recurring Transaction Add-ons
    {
      id: 'ADDON_TX_RECURRING_500_PRICE',
      key: 'ADDON_TX_RECURRING_500_PRICE',
      label: '+500 TX Recurring Price',
      description: 'Monthly price for +500 TX recurring (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '9900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_TX_RECURRING_500_PRICE_ID',
      key: 'ADDON_TX_RECURRING_500_PRICE_ID',
      label: '+500 TX Recurring Stripe Price ID',
      description: 'Stripe Price ID for +500 TX recurring',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_TX_RECURRING_1000_PRICE',
      key: 'ADDON_TX_RECURRING_1000_PRICE',
      label: '+1000 TX Recurring Price',
      description: 'Monthly price for +1,000 TX recurring (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '17900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_TX_RECURRING_1000_PRICE_ID',
      key: 'ADDON_TX_RECURRING_1000_PRICE_ID',
      label: '+1000 TX Recurring Stripe Price ID',
      description: 'Stripe Price ID for +1,000 TX recurring',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
    {
      id: 'ADDON_TX_RECURRING_5000_PRICE',
      key: 'ADDON_TX_RECURRING_5000_PRICE',
      label: '+5000 TX Recurring Price',
      description: 'Monthly price for +5,000 TX recurring (cents)',
      category: 'ADDON_PRICING',
      dataType: 'NUMBER',
      defaultValue: '79900',
      scope: 'PLATFORM',
      required: false,
      validation: { min: 0 },
      countryCode: null,
    },
    {
      id: 'ADDON_TX_RECURRING_5000_PRICE_ID',
      key: 'ADDON_TX_RECURRING_5000_PRICE_ID',
      label: '+5000 TX Recurring Stripe Price ID',
      description: 'Stripe Price ID for +5,000 TX recurring',
      category: 'ADDON_PRICING',
      dataType: 'STRING',
      defaultValue: '',
      scope: 'PLATFORM',
      required: false,
      countryCode: null,
    },
  ]

  // Upsert all definitions
  for (const def of definitions) {
    await prisma.configurationDefinition.upsert({
      where: { key: def.key as any },
      create: def as any,
      update: def as any,
    })
  }

  console.log(`✅ Seeded ${definitions.length} configuration definitions`)
}
